<<<<<<< HEAD
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14:25:52 6/5/2025
=======
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/6/2025, 2:29:15 PM
>>>>>>> 1bf2c1a20e5fceac64fddb127486bf0f26fefbe6
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/thanh/OneDrive/Máy tính/Next_users/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/OneDrive/Máy tính/Next_users/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/OneDrive/Máy tính/Next_users/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/OneDrive/Máy tính/Next_users/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/OneDrive/Máy tính/Next_users/plugins/**/*.{js,ts,mjs}","C:/Users/thanh/OneDrive/Máy tính/Next_users/composables/**/*.{js,ts,mjs}","C:/Users/thanh/OneDrive/Máy tính/Next_users/utils/**/*.{js,ts,mjs}","C:/Users/thanh/OneDrive/Máy tính/Next_users/pages/index.vue","C:/Users/thanh/OneDrive/Máy tính/Next_users/pages/Login.vue","C:/Users/thanh/OneDrive/Máy tính/Next_users/pages/profile.vue","C:/Users/thanh/OneDrive/Máy tính/Next_users/pages/products.vue","C:/Users/thanh/OneDrive/Máy tính/Next_users/pages/Register.vue","C:/Users/thanh/OneDrive/Máy tính/Next_users/pages/poductdetail/[slug].vue","C:/Users/thanh/OneDrive/Máy tính/Next_users/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/OneDrive/Máy tính/Next_users/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/OneDrive/Máy tính/Next_users/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;