// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 09:22:24 8/5/2025
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/Next_users/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Next_users/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Next_users/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Next_users/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Next_users/plugins/**/*.{js,ts,mjs}","D:/Next_users/composables/**/*.{js,ts,mjs}","D:/Next_users/utils/**/*.{js,ts,mjs}","D:/Next_users/pages/index.vue","D:/Next_users/pages/Login.vue","D:/Next_users/pages/Register.vue","D:/Next_users/pages/personal/[name].vue","D:/Next_users/pages/products/[name].vue","D:/Next_users/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Next_users/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Next_users/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;