// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16:10:47 22/4/2025
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/thanh/Next_users/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/Next_users/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/Next_users/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/Next_users/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/Next_users/plugins/**/*.{js,ts,mjs}","C:/Users/thanh/Next_users/composables/**/*.{js,ts,mjs}","C:/Users/thanh/Next_users/utils/**/*.{js,ts,mjs}","C:/Users/thanh/Next_users/pages/index.vue","C:/Users/thanh/Next_users/pages/Login.vue","C:/Users/thanh/Next_users/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/Next_users/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thanh/Next_users/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;